@startuml
start
:Пользователь заходит на блог;
:Пользователь выбирает реку или озеро;
if (Доступна ли информация?) then (да)
  :Отобразить информацию;
else (нет)
  :Показать "Информация недоступна";
endif
stop
@enduml

@startuml
start
:Администратор входит в систему;
:Администратор выбирает "Управление постами";
:Администратор добавляет новый пост;
:Администратор сохраняет пост;
stop
@enduml
