@startuml
actor Пользователь
actor Администратор

Пользователь --> (Просмотр рек и озер)
Пользователь --> (Поиск информации)
Пользователь --> (Комментирование постов)
Администратор --> (Управление постами)
Администратор --> (Модерация комментариев)

(Просмотр рек и озер) --> (Поиск информации)
@enduml
